### ISSUE TITLE
Opportunities should be open to the public

### ISSUE THREAD

**Issue by stabback** [Volunteer-Victoria/volunteer-victoria-community#62]
TO BE CONFIRMED WITH VV

Non-users should be able to browse and read opportunities without an account.

**Comment by will-sonnex** [comment]
Confirmed, and unauthenticated access should not be able to see any personal information, including name, phone number, email. Unauthenticated users should not be able to contact posters, or post opportunities themselves.

**Comment by stabback** [comment]
@f-algebra We're going to need to lock down personal information in the opps requests now.  Contact information should only be provided if a valid access token is supplied.

**Comment by stabback** [comment]
Started in https://github.com/Volunteer-Victoria/volunteer-victoria-community/commit/42bc1424e4510c6a692a3eb9edd2d848944378eb, all opps should now be public.  No filtering out data or linking the express interest button to a login yet.
