### ISSUE TITLE
Site needs something to tell users what it is

### ISSUE THREAD

**Issue by stabback** [Volunteer-Victoria/volunteer-victoria-community#63]
The site assumes people know what it is.  Add some sort of text or guidance to help brand new people understand the site.

**Comment by will-sonnex** [comment]
Confirmed with VV that we need something like a landing page

**Comment by stabback** [comment]
Blocked until we can get a designer or copy

**Comment by NamraataS** [comment]
Here's the link to the revised and updated landing page in Figma for feedback from Will and Josh. Once I've received your feedback and made any necessary changes, I can send it to Paulina and Lisa for feedback too. 

https://www.figma.com/file/TBokvsduubAmZI9UHoivBw/Landing-Page?node-id=141%3A2074&t=K1qGRJRzVQXdmXu9-1

@ Josh - As required, I've included the screenshots for the MUI icons.

**Comment by NamraataS** [comment]
I used a plug-in called Stark to check for accessibility. The older blue was lighter, so the contrast needed to be more. For ease of use for seniors, it's essential to meet the WCAG requirements. So I've changed the blue to ensure the landing page meets AA and AAA requirements. Let me know if you have any questions.

<img width="1440" alt="Screen Shot 2022-12-22 at 1 35 21 PM" src="https://user-images.githubusercontent.com/121319503/209409150-7b19f97c-0b77-4a4e-aa9c-eb06ca6612c6.png">
<img width="1440" alt="Screen Shot 2022-12-22 at 1 35 31 PM" src="https://user-images.githubusercontent.com/121319503/209409154-900a41af-7f3d-436b-ba1c-c4d551a08201.png">

**Comment by will-sonnex** [comment]
> Here's the link to the revised and updated landing page in Figma for feedback from Will and Josh. Once I've received your feedback and made any necessary changes, I can send it to Paulina and Lisa for feedback too.

My main feedback is I'd like a call-to-action to view opportunities without being signed in

**Comment by NamraataS** [comment]
Hey, as required, here's the updated landing page. Let me know if it requires any changes or if I can send this version to Lisa and Paulina for their feedback. Thanks! 
https://www.figma.com/file/TBokvsduubAmZI9UHoivBw/Landing-Page?node-id=175%3A2

**Comment by will-sonnex** [comment]
That looks great to me @NamraataS . I'd like to hear from @stabback since this is mostly on his side to implement. 

Let's discuss in the near future about what we want the design approval process to be (e.g. should you always just send them directly to Paulina/Lisa).
