### ISSUE TITLE
Posters should not have to reveal their email address or phone number

### ISSUE THREAD

**Issue by will-sonnex** [Volunteer-Victoria/volunteer-victoria-community#68]
Thinking of how e.g. UsedVictoria does things where the email address is hidden using a submission form and email proxy service.

**Comment by stabback** [comment]
Assuming we are going to make this a one or the other type deal?  A user must enter an email address _or_ a phone number?

**Comment by will-sonnex** [comment]
Agreed with OR but we'd need an option to let them choose to publicly expose their email address or use the proxying mechanism.
