### ISSUE TITLE
Date field on Post Opportunity should be more user friendly

### ISSUE THREAD

**Issue by will-sonnex** [Volunteer-Victoria/volunteer-victoria-community#75]
Had feedback from Sybil that it's awkward, and I assume this is because we're using ISO for input, rather than DD/MM/YYYY or similar

**Comment by stabback** [comment]
Switch to https://mui.com/x/react-date-pickers/date-picker/ from a standard `<input type="date" />`

Note - the data type is abstracted from the input, so the user should not be aware of the format we use under the hood.
